name: NeverEnoughRecipes
version: '0.4.1'
main: com.github.darksoulq.ner.NeverEnoughRecipes
api-version: '1.21'
authors: [ DarkSoul ]

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE
  bootstrap:
    AbyssalLib:
      required: true
      load: BEFORE