name: NeverEnoughRecipes
version: '1.0.0-mc.26.1.2'
main: com.github.darksoulq.ner.NeverEnoughRecipes
api-version: '26.1'
authors: [ DarkSoul ]

folia-supported: true

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE
  bootstrap:
    AbyssalLib:
      required: true
      load: BEFORE