name: NeverEnoughRecipes
version: '${version}'
main: com.github.darksoulq.ner.NeverEnoughRecipes
api-version: '${apiVersion}'
authors: [ DarkSoul ]

folia-supported: true

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE
  bootstrap:
    AbyssalLib:
      required: true
      load: BEFORE